services:
  dev:
    build:
      context: /home/peter
      dockerfile: Projects/DevEnv/Dockerfile
    container_name: dev
    ports:
      - "5000:5000"
    volumes:
      - /home/peter/Projects:/workspace
      # alternative: clone nvim config in Dockerfile (git clone https://github.com/ptyszkow/nvim)
      # - /home/peter/.config/nvim:/root/.config/nvim
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: bash
